---
- hosts: localhost
  vars:
        key_name: "skilldemon"
  tasks:
    - name: Launch AWS EC2 instance
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        region: "{{ region }}"
        instance_tags:
          Name: "{{ instance_name }}"
        assign_public_ip: no
      register: ec2

    - name: Add hosts to group
      add_host: hostname={{ item.public_ip }} groupname=skilldemon ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/skilldemon.pem
      with_items: ec2.instances

    - name: Wait for SSH
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

    - name: Set public_ip
      shell: echo "{{ item.public_ip }}" > tmp_ip
      with_items: ec2.instances


- name: Configure Tomcat
  hosts: skilldemon
  sudo: yes
  gather_facts: false
  tasks:

    - apt: name=tomcat7 update_cache=yes

    - name: Tomcat service
      service: name=tomcat7 state=started enabled=yes

    - name: Wait for Tomcat
      wait_for: port=8080 delay=2

